### ISSUE TITLE
Repo ready to be tested with more data.

### ISSUE THREAD

**Issue by FabianSantano** [MatthewSanchez-202/MBARI-Expedition-API-Integration#11]

**Comment by MBARIMike** [comment]
Testing now, following directions in [README.md](https://github.com/MatthewSanchez-202/MBARI-Expedition-API-Integration/blob/a1b281224147785e719a802d8c07bad65adf467f/README.md):
```
➜  GitHub git clone git@github.com:MatthewSanchez-202/MBARI-Expedition-API-Integration.git
➜  GitHub cd MBARI-Expedition-API-Integration
➜  MBARI-Expedition-API-Integration git:(main) python3 -m venv venv
➜  MBARI-Expedition-API-Integration git:(main) ✗ source venv/bin/activate
(venv) ➜  MBARI-Expedition-API-Integration git:(main) ✗ pip install -r requirements.txt 
```
(I needed to add the `-r` to the pip install command.) The next step states: Put database information into environment variables. Are there any hints for what these are? I suspect that they might be related to [these lines in main.py](https://github.com/MatthewSanchez-202/MBARI-Expedition-API-Integration/blob/a1b281224147785e719a802d8c07bad65adf467f/main.py#L18-L21), but it's not clear.

**Comment by FabianSantano** [comment]
They are related to those lines.
SERVER would be the server where the mbari database is hosted . For our
case the docker container with the database was hosted locally so we put
"localhost"
DATABASE would be the name of the database being used , in our case we
named the database MBARI

USERNAME = 'SA'
PASSWORD is the password we set up when running the docker command below ,
 these lines are what connects the api to the actual database .

docker run --cap-add SYS_PTRACE -e 'ACCEPT_EULA=1' -e
'MSSQL_SA_PASSWORD=yourStrong(!)Password' -p 1433:1433 --name azuresqledge
-d mcr.microsoft.com/azure-sql-edge

**Comment by MBARIMike** [comment]
Thanks for the hints! I set hard-coded the database connection parameters (for testing) in main.py and now get this error (after doing a `pip install flask_login`):
```
(venv) ➜  MBARI-Expedition-API-Integration git:(main) ✗ flask --debug run
 * Serving Flask app 'main.py'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 835-990-681
127.0.0.1 - - [10/May/2024 13:20:10] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/main.py", line 103, in homepage
    return render_template('home.html', user=user)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mccann/GitHub/MBARI-Expedition-API-Integration/venv/lib/python3.11/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: home.html
```
Any hints for me on this? I do see a home.html file, but maybe a user login is required (?)

**Comment by nikhilkul12** [comment]
I

**Comment by nikhilkul12** [comment]
In the case of login, you would have to create Google OAuth credentials. I am linking a video below made by fabian on how to set that up. 
[Google Oauth ](https://www.loom.com/share/3acf4e7d44bd4e6c86ca1ddfbbcf63fa?sid=8c9bc293-56ca-4f22-a93d-ee7e5dffa9e0)

**Comment by FabianSantano** [comment]
Hello Mike I just got home . The error you are encountering is because the
home.html file was supposed to be in the templates folder and it wasn't .
I've fixed it on the git repo so the html file is within the templates
folder. And also as nikhil stated you will have to create google
authentication credentials so be allowed to use the google Oauth .
